config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :details
  root 'details#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
	has_attached_file :image, styles: { :large => "600*600>", :thumb => "150*150>", :medium => "250*250>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
validate :validate_username
validates_format_of :password, with: /^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$&*]).{12,}$/, :multiline => true

def validate_username
  if User.where(email: username).exists?
    errors.add(:username, :invalid)
  end
end

def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
end


  has_many :details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
	 devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
	 devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
	 devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :find_detail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  

  def index
  	@details = Detail.all
  end


  def show
  end
  

  def new
  	@detail = current_user.details.new
  end
  

  def edit
  end


  def create
  	@detail = current_user.details.new(detail_params)
  
  	if @detail.save
  		redirect_to @detail
  	else
  		render 'new'
  	end
  end


  def update
  
  	if @detail.update(detail_params)
  		redirect_to @detail
  	else
  		render 'edit'
  	end
  end


  def destroy
  	@detail.destroy
  	redirect_to root_path
  end


  private

  def find_detail
  	@detail = Detail.find(params[:id])
  end

  def detail_params
  	params.require(:detail).permit(:title, :body, :image)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for @detail, html: { multipart: true} do |f| %>
	<%= f.label :image %><br>
	<%= f.file_field :image %><br>
	<br>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
	<% end %>

app/views/details/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/details/index.html.erb
<table style="width:100%" align ="center">
  <tr>
    <th>Title</th>
    <th>User Email</th> 
    <th>Image</th>
    <th>Information</th>
  </tr>
  <br>
  <tr>
	<% @details.each do |detail| %>
	<td><h3><%= detail.title %></h3></td>
	<td><h4><%= detail.user.email %></h4></td>
	<td><%= image_tag detail.image.url(:thumb) %></td>
	<td><div><%= truncate(detail.body, :length =>60) %></div></td>
	<td><%= link_to "Read Detail", detail %></td>
  </tr>
<% end %>

app/views/details/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/details/show.html.erb
<table style="width:100%">
	<tr>
		<th><div class="field">
				<h1><%= @detail.title %></h1>
			</div>
		</th>

		<th>
			</div>
				<%= @detail.body %>
			</div>
		</th>
		<br>
		<th>
			<div class="field">
				<%= image_tag @detail.image.url{:medium} %>
			</div>
		</th>
	</tr>


<tr>
	<div>
		<% if @detail.user == current_user %>
  		<th><%= link_to "Edit", edit_detail_path(@detail) %></th>
  		<th><%= link_to "Delete", detail_path(@detail), method: :delete, data: {confirm: "Are you sure ?"} %></th>
		<% end %>
	</div>
</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lib</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_path %><br><br>
  <%= link_to "New Post", new_detail_path %><br><br>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= link_to "Sign Up", new_user_registration_path %><br><br>
  <%= link_to "Sign in", new_user_session_path  %><br><br>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %><br><br>
  <br>
  <div class="field">
    <% if user_signed_in? %>
      <div>Signed in as... <%= current_user.email %></div>
    <% end %>
  </div>

<%= yield %>
  </body>
</html>